### ISSUE TITLE
Update abseil-cpp

### ISSUE THREAD

**Issue by comcloudway** [flxzt/ink-stroke-modeler-rs#2]
Hey,
can you update `abseil-cpp`?

Musl libc recently removed `off64_t` and `abseil-cpp` renamed `off64_t` to `off_t`,
however, the `abseil-cpp` version you are using still uses `off64_t` which is why `rnote` fails to build on Musl libc system (like Alpine and postmarketOS).

I considered creating a PR, but I wasn't sure whether you wanted to check out a specific abseil version instead of just the latest commit, [like I did](https://github.com/comcloudway/ink-stroke-modeler-rs/commit/8699cd6e7fc6569edbb3eedaea391d07e4640710).

[One of the changes line in the `abseil-cpp` repo](https://github.com/abseil/abseil-cpp/blob/70172ada858b8739ce07e8c2f1ecd8c11c8768c7/absl/base/internal/direct_mmap.h#L75), changed by [this](https://github.com/abseil/abseil-cpp/commit/4500c2fada4e952037c59bd65e8be1ba0b29f21e) commit.

**Comment by flxzt** [comment]
Sure! My initial plan was to check out the LTS tags, but if non-standard C++ is used and because of that it does not build any more, then it seems fine to me to check out the latest commit where this is fixed.

should be fixed with 458d0247cec9d1a3d39e3922259945eec8b31625 .

**Comment by comcloudway** [comment]
Thanks, a lot
